### ISSUE TITLE
Sigma

### ISSUE THREAD

**Issue by savvyspoon** [preludeorg/community#11]
What do you think about adding a section for sigma rules?  I always find myself cross referencing against other open source tools like sigma and Mitre.

**Comment by privateducky** [comment]
Definitely. There are a number of detection/SIEM-related classification systems on our road map, sigma and CAR among them. We're tackling this in 3 stages right now:

1. We'll be introducing a new "plugins" section in the near future. This section, similar to what I designed in Caldera, will allow you to override or extend any part of the system. This will include opening the door for custom plugins to extend the TTP format which we use. 
2. We'll be introducing built-in SIEM support as part of the app, which will allow you to tie in popular providers & classification systems for detection.
