### ISSUE TITLE
[Feature enhancement] Support for multiple payloads for a TTP

### ISSUE THREAD

**Issue by tr4cefl0w** [preludeorg/community#242]
Currently, to my understanding, only a single payload is supported by TTP, even with multiple variants. 

In many cases, just like why the variant feature is useful, there are many ways to achieve a goal with payloads that work differently. 

Another example would be that a TTP would have 2 stages, like a dropper and the actual payload so when testing an EDR, we could test detection on one or the other depending on the WinAPI calls used.

It would be nice if TTPs could have support for multiple payloads.

**Comment by khyberspache** [comment]
Wouldn't the dropper handle the ingress and execution of the second payload?
