### ISSUE TITLE
Schism-ftp: instruction failure

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/community#254]
When deploying chains against schism-ftp that is connected to a redirector 
`[-] Instruction failed: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
`

**Comment by khyberspache** [comment]
Think this is resolved here: https://github.com/preludeorg/community/commit/c73bfd95c11b5e0079e4206e9a4eced8abd0b9d8

Test again
