### ISSUE TITLE
Editor no longer available

### ISSUE THREAD

**Issue by HarveyVega** [preludeorg/community#34]
EDIT: I should note that restarting Operator did not fix it but rebooting the OS did. 

I am walking through the training modules and successfully got the flag for Intro>Emulation>Import a New Procedure. I cloned the community git locally and added the 58282d96-4b91-49e8-adaf-eaa3db921b7a.yml file to the execution folder. Then I went to the editor to upload it and instead of uploading the individual file I opted to upload the folder. I got a pop up stating it was done but now when I click on the editor I get the following Unhandled Exception which I've attached a screenshot of 
![2021-01-21_18-07](https://user-images.githubusercontent.com/14943426/105427910-d3a6f380-5c13-11eb-9a84-60c0289b6d79.png)

I am running Operator 0.9.13 on Ubuntu 20.04.1 LTS 64bit.

**Comment by khyberspache** [comment]
We are tracking a similar bug on our operator-support repo

**Comment by HarveyVega** [comment]
Whoops, I can close this as I definitely should have posted/checked over there.

**Comment by HarveyVega** [comment]
Posted over in the operator-support repo
