### ISSUE TITLE
Cannot complete basic training as docs have been moved

### ISSUE THREAD

**Issue by macdonsp** [preludeorg/community#534]
I have been working through training in the community edition and it looks like you cannot progress through the 'basic' module as the docs have been moved as part of the 1.7 release to doc.prelude.org

https://github.com/preludeorg/community/blob/50d1a3609093c3f2bf0ef93cd7e08db06085d109/training/introduction/basic/1655c859-17dd-4b53-9ae6-3e895afb8cc7.yml#L18

**Comment by makk94** [comment]
Hey - we actually did a rewrite of our training and slimmed it down a bit. The new stuff is now up and no longer has this issue

Thanks!
